### ISSUE TITLE
Missing icon for 'published' state

### ISSUE THREAD

**Issue by keybits** [tdreyno/middleman-blog-editor-issues#2]
As per the issue title and shown below:

![2013-01-03_002615](https://f.cloud.github.com/assets/809823/39679/506f0368-553c-11e2-80be-a173cb353389.png)

**Comment by tdreyno** [comment]
Heh... that's actually correct. It's an 'x' in a box. Though now that you mention it, it is hauntingly reminiscent of IE's missing image logo.

**Comment by tdreyno** [comment]
Maybe I'll just use an unstyled checkbox instead of getting fancy.
