### ISSUE TITLE
Unpublished Flag Not Working

### ISSUE THREAD

**Issue by nayefc** [tdreyno/middleman-blog-editor-issues#3]
When marking an article as unpublished, it appears on my blog.

**Comment by tdreyno** [comment]
Is this during preview only or build as well?

Can you paste the "frontmatter" of the article file (on disk, not through the blog editor)? The frontmatter is the stuff at the top between the `---` lines.

**Comment by nayefc** [comment]
That is during build and preview as well. The top lines are:

---

title: Test Article
published: false

## blog_editor_id: 8

## 

Nayef Copty
nrcopty@gmail.com
http://nayefcopty.com

**Comment by tdreyno** [comment]
Preview mode shows unpublished articles so you can develop them, but they shouldn't be built when running `middleman build`. Looks like the blog editor is correctly setting `published: false`, so this may be a `middleman-blog` bug.

What version of `middleman-blog` are you running?

**Comment by nayefc** [comment]
I'm running middleman-blog version 3.2.0. Does it have an issue when setting the published flag as false? Isn't this the latest version of middleman-blog?

## 

Nayef Copty
nrcopty@gmail.com
http://nayefcopty.com

**Comment by tdreyno** [comment]
I can't replicate this issue with the same versions.

I have one idea though, was the article formerly built and now, after changing the check box, it's still in the output `build/` folder?

If so, Middleman doesn't remove files from `build` that no longer exist (or are unpublished) by default. Use the `--clean` flag to change this behavior:

```
middleman build --clean
```

If your built article existed in build before, it will now be removed if it is unpublished.

**Comment by nayefc** [comment]
I have live reload on. Could that be the issue?

I cannot find the article in /build, so I have no idea how it's appearing on localhost:4567/blog. I did a clean build and it said everything was identical. Yet I can see the unpublished article in /blog.  

## 

Nayef Copty
nrcopty@gmail.com
http://nayefcopty.com

**Comment by tdreyno** [comment]
Sounds like everything is working as expected. To reiterate:

Unpublished article are supposed to be visible in preview (localhost:4567), but they will not be built into build.
