### ISSUE TITLE
Compatible with MM 3.1.0?

### ISSUE THREAD

**Issue by stoplion** [tdreyno/middleman-blog-editor-issues#6]
Looks like MM Editor depends on middleman-core (= 3.0.8.pre.1) and MM 3.1.0 is depending on middleman-core (3.1.5)? Is there a way to make it compatible?

**Comment by tdreyno** [comment]
Which version are you using? Can you send me your `Gemfile.lock`?

**Comment by jina** [comment]
I think I might be having a similar issue. Here's what I see:

```Bundler could not find compatible versions for gem "middleman-core":
  In Gemfile:
    middleman (>= 0) ruby depends on
      middleman-core (= 3.1.6) ruby

``````
middleman-core (3.0.8.pre.1)```
``````

This is on a fresh install of middleman, just now getting around to trying out the blog editor.

**Comment by tdreyno** [comment]
I think I see the problem... one moment

**Comment by tdreyno** [comment]
Just release `v0.4.1` with Middleman `3.1` support.

**Comment by jina** [comment]
rad, thanks. I'll give it a try. :)

**Comment by jina** [comment]
bundled and things worked fine. Thanks again!
